// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moodle.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moodle.Infrastructure.Migrations
{
    [DbContext(typeof(MoodleDbContext))]
    partial class MoodleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moodle.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Announcements", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Dobrodošli na Programiranje 1!",
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            Title = "Dobrodošli"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Prvi kolokvij održat će se sljedeći tjedan.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            Title = "Prvi kolokvij"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Dodana nova literatura za kolegij.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 3,
                            Title = "Literatura"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Predavanje iz Web programiranja pomaknuto za utorak.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 3,
                            Title = "Predavanje"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Novi sadržaj za Napredno C#.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 10,
                            Title = "Napredno predavanje"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Prvo predavanje iz Data Science.",
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 13,
                            Title = "Data Science Intro"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Priprema za Machine Learning kolokvij.",
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 13,
                            Title = "ML Kolokvij"
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Programiranje 1",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Objektno programiranje",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Baze podataka",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Web programiranje",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Napredno C#",
                            ProfessorId = 10
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Data Science",
                            ProfessorId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Machine Learning",
                            ProfessorId = 13
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", "public");

                    b.HasData(
                        new
                        {
                            UserId = 4,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 6,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 4,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 7,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 8,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 9,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 11,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2025, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 12,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2025, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 11,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2025, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Materials", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Uvod u C#",
                            ProfessorId = 2,
                            Url = "https://example.com/csharp"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "OOP principi",
                            ProfessorId = 2,
                            Url = "https://example.com/oop"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            CreatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SQL osnove",
                            ProfessorId = 3,
                            Url = "https://example.com/sql"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            CreatedAt = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HTML & CSS",
                            ProfessorId = 3,
                            Url = "https://example.com/html-css"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            CreatedAt = new DateTime(2025, 12, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "LINQ u C#",
                            ProfessorId = 2,
                            Url = "https://example.com/linq"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Napredni LINQ",
                            ProfessorId = 10,
                            Url = "https://example.com/linq-advanced"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 6,
                            CreatedAt = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Python Basics",
                            ProfessorId = 13,
                            Url = "https://example.com/python"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 7,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "ML Algorithms",
                            ProfessorId = 13,
                            Url = "https://example.com/ml"
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Dobrodošao na kolegij!",
                            ReceiverId = 4,
                            SenderId = 2,
                            SentAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hvala!",
                            ReceiverId = 2,
                            SenderId = 4,
                            SentAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Jesi li riješio zadatak?",
                            ReceiverId = 6,
                            SenderId = 5,
                            SentAt = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Molim te pošalji zadaću.",
                            ReceiverId = 7,
                            SenderId = 3,
                            SentAt = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Poslao sam svoj projekt.",
                            ReceiverId = 3,
                            SenderId = 8,
                            SentAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Pozdrav profesore!",
                            ReceiverId = 10,
                            SenderId = 9,
                            SentAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Dobrodošao!",
                            ReceiverId = 9,
                            SenderId = 10,
                            SentAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Pozdrav profesore!",
                            ReceiverId = 13,
                            SenderId = 11,
                            SentAt = new DateTime(2025, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Pošaljem zadatak danas.",
                            ReceiverId = 13,
                            SenderId = 12,
                            SentAt = new DateTime(2025, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@moodle.com",
                            Password = "admin123",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "prof1@moodle.com",
                            Password = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lanavukadin@moodle.com",
                            Password = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student1@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student2@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student3@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student4@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student5@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student6@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "prof3@moodle.com",
                            Password = "prof123",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student7@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student8@moodle.com",
                            Password = "student123",
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "prof4@moodle.com",
                            Password = "prof123",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Professor")
                        .WithMany("Announcements")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Course", b =>
                {
                    b.HasOne("User", "Professor")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Material", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Professor")
                        .WithMany("Materials")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Message", b =>
                {
                    b.HasOne("User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("CoursesTaught");

                    b.Navigation("Enrollments");

                    b.Navigation("Materials");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
